server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: DOCTOR-SERVICE
          uri: lb://DOCTOR-SERVICE
          predicates:
            - Path=/doctor/**
        - id: PATIENT-SERVICE
          uri: lb://PATIENT-SERVICE
          predicates:
            - Path=/patient/**
